/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.ferracini;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void getAGreeting() {
        App classUnderTest = new App();
        assertEquals("Hello world.",classUnderTest.getGreeting());
    }
}
